// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8AoTJ3HVi0Z1EB2Awrb4vkP3fEKMD_8I',
    appId: '1:968590909734:web:ac4477efb518ba502161e7',
    messagingSenderId: '968590909734',
    projectId: 'swiftride-94918',
    authDomain: 'swiftride-94918.firebaseapp.com',
    storageBucket: 'swiftride-94918.firebasestorage.app',
    measurementId: 'G-TWNY3QTXZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD064lZoZRIIPVsjYtWuvnyUqhiODGgj3o',
    appId: '1:968590909734:android:10725660c7c1f5142161e7',
    messagingSenderId: '968590909734',
    projectId: 'swiftride-94918',
    storageBucket: 'swiftride-94918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbg_YcMjJSUFEeDpU-A6uN9YWTFUkwqEw',
    appId: '1:968590909734:ios:25001c3a4ed791002161e7',
    messagingSenderId: '968590909734',
    projectId: 'swiftride-94918',
    storageBucket: 'swiftride-94918.firebasestorage.app',
    iosBundleId: 'com.example.swiftRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbg_YcMjJSUFEeDpU-A6uN9YWTFUkwqEw',
    appId: '1:968590909734:ios:25001c3a4ed791002161e7',
    messagingSenderId: '968590909734',
    projectId: 'swiftride-94918',
    storageBucket: 'swiftride-94918.firebasestorage.app',
    iosBundleId: 'com.example.swiftRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8AoTJ3HVi0Z1EB2Awrb4vkP3fEKMD_8I',
    appId: '1:968590909734:web:1ea6ed3de66d6bd52161e7',
    messagingSenderId: '968590909734',
    projectId: 'swiftride-94918',
    authDomain: 'swiftride-94918.firebaseapp.com',
    storageBucket: 'swiftride-94918.firebasestorage.app',
    measurementId: 'G-RRWJZXF6GX',
  );
}
